const $=id=>document.getElementById(id);const state={chat:null,chats:[],videos:[]};
async function api(path,opt){const r=await fetch('/api'+path,opt);if(!r.ok)throw new Error(await r.text());return r.json()}
async function loadChats(){state.chats=await api('/chats?search='+encodeURIComponent($('chat-filter').value));$('chat-list').innerHTML=state.chats.map(c=>`<div class="chat-item ${state.chat?.id===c.id?'active':''}" data-id="${c.id}">${esc(c.title)}</div>`).join('')||'<small>No conversations yet</small>';document.querySelectorAll('.chat-item').forEach(x=>x.onclick=()=>openChat(x.dataset.id))}
async function loadVideos(){state.videos=await api('/videos');$('video-scope').innerHTML='<option value="">All processed videos</option>'+state.videos.map(v=>`<option value="${v.video_id}">${esc(v.filename)}</option>`).join('')}
async function newChat(){state.chat=await api('/chats',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({title:'New surveillance chat',video_id:$('video-scope').value||null})});render([]);loadChats()}
async function openChat(id){state.chat=await api('/chats/'+id);render(state.chat.messages);loadChats()}
function render(messages){$('messages').innerHTML=messages.length?'':'<div class="welcome"><h1>Ask about your processed videos</h1><p>Answers use verified evidence.</p></div>';messages.forEach(m=>addMessage(m))}
function addMessage(m,evidence=[]){$('messages').insertAdjacentHTML('beforeend',`<article class="message ${m.role}"><div class="role">${m.role}</div><div class="message-body">${esc(m.content)}</div></article>`);if(evidence.length){const cards=evidence.map(e=>`<div class="e-card" data-event='${JSON.stringify(e).replaceAll("'","&#39;")}'><small>${e.start_sec.toFixed(1)}s–${e.end_sec.toFixed(1)}s · ${esc(e.event_type)}</small><p>${esc(e.description)}</p></div>`).join('');$('messages').insertAdjacentHTML('beforeend',`<div class="cards">${cards}</div>`);document.querySelectorAll('.e-card').forEach(c=>c.onclick=()=>showEvidence(JSON.parse(c.dataset.event))) }$('messages').scrollTop=$('messages').scrollHeight}
async function send(e){e.preventDefault();const input=$('prompt'),content=input.value.trim();if(!content)return;if(!state.chat)await newChat();addMessage({role:'user',content});input.value='';const result=await api(`/chats/${state.chat.id}/messages`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({content})});addMessage(result.message,result.evidence);loadChats()}
async function showEvidence(e){const d=await api('/events/'+e.event_id+'/evidence');$('evidence').classList.remove('hidden');$('evidence-title').textContent=e.event_type;$('evidence-description').textContent=d.description;$('evidence-time').textContent=`${d.start_sec.toFixed(1)}s – ${d.end_sec.toFixed(1)}s`;$('evidence-confidence').textContent=d.confidence.toFixed(2);$('evidence-anomaly').textContent=d.anomaly_category;$('evidence-video').src=d.clip_url||d.source_video_url;$('clip-link').href=d.clip_url||d.source_video_url}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
$('new-chat').onclick=newChat;$('composer').onsubmit=send;$('chat-filter').oninput=loadChats;$('close-evidence').onclick=()=>$('evidence').classList.add('hidden');Promise.all([loadChats(),loadVideos()]);
